blank_issues_enabled: false
contact_links:
  - name: Spørsmål / Diskusjon
    url: https://github.com/loopwish
    about: Bruk org-siden for å finne riktig repo, eller opprett en issue i relevant repo.
